services:
  - type: web
    name: gutenread
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $RENDER_PORT --workers 1 --proxy-headers --forwarded-allow-ips='*'